### ISSUE TITLE
generate the pseudo-ground-truth segmentation masks

### ISSUE THREAD

**Issue by getterupper** [ahayler/s4c#1]
Hi, Thank you for nice work!
I'm trying to generate the pseudo-ground-truth segmentation masks myself, but I couldn't find the file 'preprocess_kitti_360_segmentation.py' you mentioned in the README.
Could you please share your way to generate them?

**Comment by ahayler** [comment]
You can find the file [here](https://github.com/ahayler/s4c/blob/main/datasets/panoptic-deeplab/tools/preprocess_kitti_360_segmentation.py).
