### ISSUE TITLE
Generate Voxel Grid

### ISSUE THREAD

**Issue by SimonGeb** [ahayler/s4c#3]
Hi,

First of all, thanks for the interesting paper and the open source code. I managed to get it all running quite quickly thanks to the clear documentation! I now have the depth and segmentation images of a custom input image.

I was wondering if it is possible to generate voxel grids from these images, and how this can be achieved.

Also, I noticed that the mentioned sample 0000.png images are not in this repository.

Thanks!

**Comment by ahayler** [comment]
Hi Simon,
thank you for the interest in our paper. I forgot to push the example images and have now added them to the repo. 
Regarding voxel grids:
Yes, this is possible. For example, during the [evaluation](https://github.com/ahayler/s4c/blob/main/scripts/benchmarks/sscbench/evaluate_model_sscbench.py) we need to convert our semantic fields to voxel grids. Also there is this [script](https://github.com/ahayler/s4c/blob/main/scripts/benchmarks/sscbench/generate_ply_sequence.py) and this [script](https://github.com/ahayler/s4c/blob/main/scripts/voxel/gen_voxelgrid_npy.py), which enable the creating of `.ply` files that represent voxel grids. We do not provide further documentation for these scripts, but they should be easy to modify to fit your needs.

Best,
Adrian
