### ISSUE TITLE
generating panoptic pseudo segmentation labels

### ISSUE THREAD

**Issue by anja-sheppard** [ahayler/s4c#5]
Hi! Great work here!

Maybe I'm missing something in the documentation, but how are you generating pseudo segmentation labels for the datasets (that aren't cityscapes)? I see the instructions for running panoptic-deeplab for cityscapes (and also the download link to the labels) but I assume you also have those for KITTI360?

**Comment by ahayler** [comment]
Thank you for the interest in our work and the question!
We do not predict the KITTI-360 labels directly, but instead map both the cityscapes and KITTI-360 labels to a unified label standard (specified in [here](https://github.com/ahayler/s4c/blob/a38d441f18c42a2ef416447f89e02ade91510989/scripts/benchmarks/sscbench/label_maps.yaml)). The labels of cityscapes and KITTI-360 are quite similar, though.
I should have made this more explicit. Therefore, I just added an FAQ section to the `README`, which address this issue.

I hope that answers your questions! If there are any other questions regarding S4C, please let me know!
