### ISSUE TITLE
How can I get the visualization results?

### ISSUE THREAD

**Issue by PhilipRS892** [ahayler/s4c#7]
Many thanks to the authors for the excellent work!!

I want to know what I should do to get the visualization results shown in the paper (as shown in Figures 3 and 7):

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/6d75adb5-827b-463e-99c7-f20b7307f0f6">

<img width="522" alt="image" src="https://github.com/user-attachments/assets/15404b15-7303-4e2b-8b45-2d52a029ca04">

Also, what should I do to get the video streaming results?

best wishes!

**Comment by ahayler** [comment]
Hey @PuTeGuo,

thank you for your interest in our work. The images are rendered `.ply` files (mostly in blender). You should be able to generate such `.ply` files with [this script](https://github.com/ahayler/s4c/blob/50982d6935af2dcee48a07b5c5bbc2a4bef9e081/scripts/benchmarks/sscbench/generate_ply_sequence.py#L79). Please note that we do not maintain any code used for generating visualizations, so you might need to debug the code to make it work.

If you would like to render the `.ply` files in Blender, you will have to adjust the shading of the voxels as shown below:

![image](https://github.com/user-attachments/assets/e3c76d90-97da-436e-b98b-273f505f39dc)

Also, I recommend setting the vertex normals to auto-smoothing.

Regarding the video outputs: These are just a long series of `.ply` files rendered in Blender. My co-author Felix Wimbauer wrote a script to then load and render these files in blender. This script isn't part of the repo and (probably) doesn't exist anymore :(

I hope this helps!

**Comment by PhilipRS892** [comment]
Thank you for your reply! This is of great help to me!

I wish you all the best!
