### ISSUE TITLE
Three categories of precision are missing in quantitative comparison results on the sscbench-kitti-360 dataset

### ISSUE THREAD

**Issue by PhilipRS892** [ahayler/s4c#8]
Hello! Thank you so much for such excellent work! This is a great contribution to community research!

However, I have a question for you. I noticed that the quantitative comparison on SSCBench-KITTI-360 in the article lacks accuracy reports for three classes, which are as follows: parking(2.31%), other-grnd(2.05%), other-struct.(4.33%). The accuracy calculation of these three categories is also missing in the evaluation code. Can you explain why?

<img width="850" alt="image" src="https://github.com/user-attachments/assets/427055cc-8f84-4083-ae3f-d0fa05b250a3">

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/a704116b-0d17-4261-a089-34fdc2f7ae16">

**Comment by ahayler** [comment]
Have you seen [this](https://github.com/ahayler/s4c#label-standard) question in the FAQ already? Let me know if that answers your questions.

All the best,
Adrian

**Comment by PhilipRS892** [comment]
Thanks for your reply! I get it!

All the best！
Pute
